import { ThemeContext } from "../../../../../@types";

export const getRules = (themeContext: ThemeContext): object => {
  const styles = themeContext.styles;
  return {
    "symbolIcon.arrayForeground": styles.basic.def.blue.pri,
    "symbolIcon.booleanForeground": styles.basic.def.blue.pri,
    "symbolIcon.classForeground": styles.basic.def.yellow.pri,
    "symbolIcon.colorForeground": styles.fill.text.sec,
    "symbolIcon.constantForeground": styles.basic.alt.mint.pri,
    "symbolIcon.constructorForeground": styles.basic.def.orange.pri,
    "symbolIcon.enumeratorForeground": styles.basic.def.mint.pri,
    "symbolIcon.enumeratorMemberForeground": styles.basic.alt.mint.pri,
    "symbolIcon.eventForeground": styles.basic.alt.red.pri,
    "symbolIcon.fieldForeground": styles.basic.alt.yellow.pri,
    "symbolIcon.fileForeground": styles.fill.text.sec,
    "symbolIcon.folderForeground": styles.fill.text.sec,
    "symbolIcon.functionForeground": styles.basic.def.orange.pri,
    "symbolIcon.interfaceForeground": styles.basic.def.mint.pri,
    "symbolIcon.keyForeground": styles.basic.alt.purple.pri,
    "symbolIcon.keywordForeground": styles.basic.def.pink.pri,
    "symbolIcon.methodForeground": styles.basic.def.orange.pri,
    "symbolIcon.moduleForeground": styles.fill.text.sec,
    "symbolIcon.namespaceForeground": styles.fill.text.sec,
    "symbolIcon.nullForeground": styles.basic.def.blue.pri,
    "symbolIcon.numberForeground": styles.basic.alt.green.pri,
    "symbolIcon.objectForeground": styles.basic.def.mint.pri,
    "symbolIcon.operatorForeground": styles.fill.text.sec,
    "symbolIcon.packageForeground": styles.fill.text.sec,
    "symbolIcon.propertyForeground": styles.basic.alt.yellow.pri,
    "symbolIcon.referenceForeground": styles.basic.def.purple.pri,
    "symbolIcon.snippetForeground": styles.basic.alt.blue.pri,
    "symbolIcon.stringForeground": styles.basic.def.brown.pri,
    "symbolIcon.structForeground": styles.basic.def.yellow.pri,
    "symbolIcon.textForeground": styles.fill.text.sec,
    "symbolIcon.typeParameterForeground": styles.basic.alt.mint.pri,
    "symbolIcon.unitForeground": styles.basic.alt.green.pri,
    "symbolIcon.variableForeground": styles.basic.alt.orange.pri,
  };
};
