import { ThemeContext } from "../../../../../@types";
import { TRANSPARENT } from "../../../../../color/constants";

export const getRules = (themeContext: ThemeContext): object => {
  const styles = themeContext.styles;
  return {
    "gitlens.closedAutolinkedIssueIconColor": styles.basic.def.purple.pri,
    "gitlens.closedPullRequestIconColor": styles.basic.def.red.pri,
    "gitlens.decorations.addedForegroundColor": styles.basic.def.green.pri,
    "gitlens.decorations.branchAheadForegroundColor": styles.basic.def.green.pri,
    "gitlens.decorations.branchBehindForegroundColor": styles.basic.def.orange.pri,
    "gitlens.decorations.branchDivergedForegroundColor": styles.basic.def.yellow.pri,
    "gitlens.decorations.branchMissingUpstreamForegroundColor": styles.basic.def.orange.pri,
    "gitlens.decorations.branchUnpublishedForegroundColor": styles.basic.def.blue.pri,
    "gitlens.decorations.branchUpToDateForegroundColor": styles.fill.text.sec,
    "gitlens.decorations.copiedForegroundColor": styles.basic.def.yellow.pri,
    "gitlens.decorations.deletedForegroundColor": styles.basic.alt.red.pri,
    "gitlens.decorations.ignoredForegroundColor": styles.fill.text.disabled,
    "gitlens.decorations.modifiedForegroundColor": styles.basic.def.blue.pri,
    "gitlens.decorations.renamedForegroundColor": styles.basic.def.yellow.pri,
    "gitlens.decorations.statusMergingOrRebasingConflictForegroundColor":
      styles.basic.def.orange.pri,
    "gitlens.decorations.statusMergingOrRebasingForegroundColor": styles.basic.alt.yellow.pri,
    "gitlens.decorations.untrackedForegroundColor": styles.basic.alt.green.pri,
    "gitlens.decorations.workspaceCurrentForegroundColor": styles.basic.def.green.pri,
    "gitlens.decorations.workspaceRepoMissingForegroundColor": styles.fill.text.disabled,
    "gitlens.decorations.workspaceRepoOpenForegroundColor": styles.basic.def.green.pri,
    "gitlens.decorations.worktreeHasUncommittedChangesForegroundColor": styles.basic.alt.blue.pri,
    "gitlens.decorations.worktreeMissingForegroundColor": styles.basic.def.red.pri,
    "gitlens.graphChangesColumnAddedColor": styles.basic.def.green.pri,
    "gitlens.graphChangesColumnDeletedColor": styles.basic.def.red.pri,
    "gitlens.graphLane10Color": styles.basic.def.orange.pri,
    "gitlens.graphLane1Color": styles.basic.def.red.pri,
    "gitlens.graphLane2Color": styles.basic.def.orange.pri,
    "gitlens.graphLane3Color": styles.basic.def.yellow.pri,
    "gitlens.graphLane4Color": styles.basic.def.green.pri,
    "gitlens.graphLane5Color": styles.basic.def.mint.pri,
    "gitlens.graphLane6Color": styles.basic.def.blue.pri,
    "gitlens.graphLane7Color": styles.basic.def.purple.pri,
    "gitlens.graphLane8Color": styles.basic.def.pink.pri,
    "gitlens.graphLane9Color": styles.basic.def.red.pri,
    "gitlens.graphMinimapMarkerHeadColor": styles.basic.def.green.pri,
    "gitlens.graphMinimapMarkerHighlightsColor": styles.basic.def.mint.pri,
    "gitlens.graphMinimapMarkerLocalBranchesColor": styles.basic.def.blue.pri,
    "gitlens.graphMinimapMarkerPullRequestsColor": styles.basic.def.purple.pri,
    "gitlens.graphMinimapMarkerRemoteBranchesColor": styles.basic.alt.mint.pri,
    "gitlens.graphMinimapMarkerStashesColor": styles.basic.def.pink.pri,
    "gitlens.graphMinimapMarkerTagsColor": styles.basic.def.yellow.pri,
    "gitlens.graphMinimapMarkerUpstreamColor": styles.basic.alt.green.pri,
    "gitlens.graphScrollMarkerHeadColor": styles.basic.def.green.sec,
    "gitlens.graphScrollMarkerHighlightsColor": styles.basic.def.mint.sec,
    "gitlens.graphScrollMarkerLocalBranchesColor": styles.basic.def.blue.sec,
    "gitlens.graphScrollMarkerPullRequestsColor": styles.basic.alt.purple.sec,
    "gitlens.graphScrollMarkerRemoteBranchesColor": styles.basic.alt.mint.sec,
    "gitlens.graphScrollMarkerStashesColor": styles.basic.def.pink.sec,
    "gitlens.graphScrollMarkerTagsColor": styles.basic.def.yellow.sec,
    "gitlens.graphScrollMarkerUpstreamColor": styles.basic.alt.green.sec,
    "gitlens.gutterBackgroundColor": styles.bg.solid.surface,
    "gitlens.gutterForegroundColor": styles.fill.text.sec,
    "gitlens.gutterUncommittedForegroundColor": styles.basic.alt.blue.pri,
    "gitlens.launchpadIndicatorAttentionColor": styles.basic.def.orange.pri,
    "gitlens.launchpadIndicatorAttentionHoverColor": styles.basic.def.orange.sec,
    "gitlens.launchpadIndicatorBlockedColor": styles.basic.def.red.pri,
    "gitlens.launchpadIndicatorBlockedHoverColor": styles.basic.def.red.sec,
    "gitlens.launchpadIndicatorMergeableColor": styles.basic.def.green.pri,
    "gitlens.launchpadIndicatorMergeableHoverColor": styles.basic.def.green.sec,
    "gitlens.lineHighlightBackgroundColor": styles.basic.neutral.sep,
    "gitlens.lineHighlightOverviewRulerColor": styles.basic.neutral.sep,
    "gitlens.mergedPullRequestIconColor": styles.basic.def.purple.pri,
    "gitlens.openAutolinkedIssueIconColor": styles.basic.def.green.pri,
    "gitlens.openPullRequestIconColor": styles.basic.def.green.pri,
    "gitlens.trailingLineBackgroundColor": TRANSPARENT,
    "gitlens.trailingLineForegroundColor": styles.fill.text.ghost,
    "gitlens.unpublishedChangesIconColor": styles.basic.alt.green.pri,
    "gitlens.unpublishedCommitIconColor": styles.basic.def.green.pri,
    "gitlens.unpulledChangesIconColor": styles.basic.def.orange.pri,
  };
};
