name: Deploy Extension

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release
        uses: actions/checkout@v3.5.3
        with:
          ref: release
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies & build
        run: |
          npm ci
          npm run build
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
