name: Release Check

on:
  pull_request:
    branches:
      - release

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: ".nvmrc"

      - name: Get the latest version
        id: get_latest_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          latest_version=$(echo $latest_tag | sed "s/v//")
          echo "latest_version=$latest_version" >> "$GITHUB_OUTPUT"
          echo "Latest version: $latest_version"

      - name: Get the proposed version
        id: get_proposed_version
        run: |
          proposed_version=$(node -p "require('./package-lock.json').version")
          echo "proposed_version=$proposed_version" >> "$GITHUB_OUTPUT"
          echo "Proposed version: $proposed_version"

      - name: Check version
        env:
          latest_version: ${{ steps.get_latest_version.outputs.latest_version }}
          proposed_version: ${{ steps.get_proposed_version.outputs.proposed_version }}
        run: npx semver -r ">$latest_version" "$proposed_version" > /dev/null && echo "Proposed version is valid" || (echo "Proposed version is invalid" && exit 1)

      - name: Check change log
        env:
          proposed_version: ${{ steps.get_proposed_version.outputs.proposed_version }}
        run: |
          proposed_version_for_regex=$(echo $proposed_version | sed "s/\./\\\\./g")
          grep -Po "## \[$proposed_version_for_regex\] - \d{4}-\d{2}-\d{2}" CHANGELOG.md > /dev/null && echo "Change log is valid" || (echo "Change log is invalid" && exit 1)
