name: Release Check

on:
  pull_request:
    branches:
      - release

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: ".nvmrc"
      - name: Install semver
        run: npm install semver
      - name: Get latest version
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          latest_version=$(echo $latest_tag | sed 's/v//')
          echo "Latest version: $latest_version"
      - name: Get proposed version
        run: |
          proposed_version=$(node -p "require('./package-lock.json').version")
          echo "Proposed version: $proposed_version"
      - name: Check version
        run: npx semver -r ">$latest_version" "$proposed_version" > /dev/null
      - name: Check change log
        run: |
          proposed_version_for_regex=$(echo $proposed_version | sed 's/\./\\./g')
          grep -E '## \[$proposed_version_for_regex] - [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}' CHANGELOG.md
