name: Release & Deploy

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release
        uses: actions/checkout@v3.5.3
        with:
          ref: release
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: ".nvmrc"
      - name: Build artifacts
        run: |
          npm ci
          npm run build
          npm install -g @vscode/vsce
          vsce package
      - name: Create release tag
        id: create_release_tag
        run: |
          release_version=$(node -p "require('./package-lock.json').version")
          release_tag="v$release_version"
          echo "release_version=$release_version" >> "$GITHUB_OUTPUT"
          git tag $release_tag
          echo "release_tag=$release_tag" >> "$GITHUB_OUTPUT"
          echo "Release tag created: $release_tag"
          git push origin $release_tag
      - name: Prepare release
        id: prepare_release
        env:
          release_version: ${{ steps.create_release_tag.outputs.release_version }}
          release_tag: ${{ steps.create_release_tag.outputs.release_tag }}
        run: |
          release_version_for_regex=$(echo $release_version | sed "s/\./\\\\./g")
          release_hightlight=$(grep -P '(?<=## \[$release_version_for_regex\] - \d{4}-\d{2}-\d{2} - ).*' ./CHANGELOG.md)
          release_name=$(echo $tag_name + " - " + $release_hightlight)
          release_body=$(grep -Pzo '(?ms)(?<=## \[1\.1\.0\] - \d{4}-\d{2}-\d{2} - $release_highlight\n).*?(?=(^## ))' ./CHANGELOG.md)
          echo "release_name=$release_name" >> "$GITHUB_OUTPUT"
          echo "release_body=$release_body" >> "$GITHUB_OUTPUT"
      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        env:
          release_tag: ${{ steps.create_release_tag.outputs.release_version }}
          release_name: ${{ steps.prepare_release.outputs.release_name }}
          release_body: ${{ steps.prepare_release.outputs.release_body }}
        with:
          tag_name: $release_tag
          name: $release_name
          body: $release_body
          files: |
            ./*.vsix
